### ISSUE TITLE
Some status effects in Japanese or missing from minibox

### ISSUE THREAD

**Issue by JesterWizard** [MokhaLeee/fe8u-cskillsys-kernel#181]
I've identified the following effects are in Japanese in the minibox 

- Attack
- Defense
- Avoid
- Critical
- Defense-
- Res-

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/6e0e6e7b-9bb3-4b4f-abba-13e64dd0611b)

And the following statuses either show a blank space where text should be, or they don't trigger the text display at all

- Sick
- Recover

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/47f9dde2-dbbb-42b2-b0a9-a66b559aff3b)

I'm aware of three more statuses 'Heavy Gravity' and 'Panic' and 'Weaken' that don't even display in the unit menu

![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/164426396/75441abd-792a-4eca-80ff-35802415cd19)

**Comment by MokhaLeee** [comment]
My test:
- Sick
- Recover
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/965f160c-e821-4381-b025-9556aed10a2f)

- heavy gravity
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/7227625e-a275-4839-a40f-34081ac09dca)
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/e153852e-b789-4060-859e-0065c01c08ae)

- Panic
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/9d68183b-485f-4297-a6c6-23eefeb98412)
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/39708484-2da2-452b-a987-e28843e7208e)


- Weaken
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/60f66a26-459c-4f2a-8488-c84f2c2f9f11)
![image](https://github.com/MokhaLeee/fe8u-cskillsys-kernel/assets/89029102/66bab3ce-947e-4231-8229-9b85ccc07084)

All the results are in line with expectations, I wonder if it's because your test method that causes some issue?

> the following effects are in Japanese in the minibox

Maybe you didn't realize that the original fe8u vanilla game did the same.  And I think it's cool to mix in some Japanese and Chinese characters

**Comment by MokhaLeee** [comment]
If you don't know how to directly write the ram data, you can call api to give unit status.
